apiVersion: v1
kind: Service
metadata:
  name: bel-mes-backend-svc
  labels:
    app: bel-mes-backend
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: bel-mes-backend
