apiVersion: apps/v1
kind: Deployment
metadata:
  name: bel-fastapi-deployment
  labels:
    app: bel-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bel-fastapi
  template:
    metadata:
      labels:
        app: bel-fastapi
    spec:
      hostNetwork: true  # Use host network to access external services
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: bel-fastapi-container
        image: bel-fastapi-app:v1.0.3
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
          hostPort: 8002  # Map to host port
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bel-fastapi-service
spec:
  selector:
    app: bel-fastapi
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 32000
  type: NodePort