apiVersion: v1
kind: Service
metadata:
  name: bel-mes-backend-service
spec:
  selector:
    app: bel-mes-backend
  ports:
  - port: 8002
    targetPort: 8002
  type: LoadBalancer  # This will make the service accessible from outside the cluster
